Config = {}

Config.Version = 1.0

Config.EnableAC = true -- Enable all detections (This needs to be turned on for the anticheat to work)

--Settings
Config.Webhook = "https://discordapp.com/api/webhooks/857960554370301962/2aAdDrLbUiKl1vUfXOEWdGMJQDNSC2VPzXCjurApLlF1eAazMVrjTqgCxQQTcGmDi2Tm" -- Discord Webhook

Config.KickReason = "You have been permanently banned from this server! [Relog for more information]"

--[Server Secuirty]
Config.GlobalBan = true -- Enable the global banlist
Config.Bypass = { -- Bypass for the globalban system.
    "steam:110000135f90e2b", -- Identifiers here
    "ip:123"
}

Config.AntiResourceStop = false -- Prevents Cheaters from Stopping/Starting new Resource
Config.AntiResource = false -- Whitelisted Resource true or false
Config.WhitelistedResources = { -- If you get banned and the anticheat logs something like this "Resource metadata not valid in resource: or Abnormal resource injection" put here the resources that are causing that errors and everything should be fixed.
	["discord-screenshot"] = true,
	["screenshot-basic"] = true,
	["mumble-voip"] = true,
}

Config.EnableScreenshot = true -- Sending screenshot on ban to your discord logs

Config.AntiVPN = false -- Rejecting players using VPN

Config.ForceDiscord = false --Force them to have discord connected with fivem
Config.ForceDiscordConsoleLogs = true

Config.ForceSteam = true --Force them to have steam open
Config.ForceSteamConsoleLogs = true

--[AI Detection, this requires you to have Config.EnableScreenshot to true with screenshot-basic ]
Config.DetectionAI = true -- Checking players screen every 15 sec if the player has a lua menu open it will ban the player, you can change checking time below.
Config.CheckMS = 15000 -- Every 15000ms it will check players screen, if there is bad performance you can change it to 30000ms (30 sec)

--[Weapons]
Config.GiveWeaponsProtection = true -- If cheater tries to give weapons to another player
Config.WeaponProtection = true -- if cheater tries to give a blacklisted weapon from their mod menu to another player.
Config.AntiExplosiveBullets = true -- Detects if players have Explosive Weapons.
Config.MaxWeaponAmmo = 250 -- Max ammo you can have in your gun on your server

Config.AntiWeaponDamageChange = true
Config.WeaponDamages = {
	[-1357824103] = { damage = 34, name = "AdvancedRifle"},
    [453432689] = { damage = 26, name = "Pistol"},
    [1593441988] = { damage = 27, name = "CombatPistol"},
    [584646201] = { damage = 25, name = "APPistol"},
    [-1716589765] = { damage = 51, name = "Pistol50"},
    [-1045183535] = { damage = 160, name = "Revolver"},
    [-1076751822] = { damage = 28, name = "SNSPistol"},
    [-771403250] = { damage = 40, name = "HeavyPistol"},
    [137902532] = { damage = 34, name = "VintagePistol"},
    [324215364] = { damage = 21, name = "MicroSMG"},
    [736523883] = { damage = 22, name = "SMG"},
    [-270015777] = { damage = 23, name = "AssaultSMG"},
    [-1121678507] = { damage = 22, name = "MiniSMG"},
    [-619010992] = { damage = 27, name = "MachinePistol"},
    [171789620] = { damage = 22, name = "CombatPDW"},
    [487013001] = { damage = 58, name = "PumpShotgun"},
    [2017895192] = { damage = 40, name = "SawnoffShotgun"},
    [-494615257] = { damage = 32, name = "AssaultShotgun"},
    [-1654528753] = { damage = 14, name = "BullpupShotgun"},
    [984333226] = { damage = 117, name = "HeavyShotgun"},
    [-1074790547] = { damage = 30, name = "AssaultRifle"},
    [-2084633992] = { damage = 32, name = "CarbineRifle"},
    [-1063057011] = { damage = 32, name = "SpecialCarbine"},
    [2132975508] = { damage = 32, name = "BullpupRifle"},
    [1649403952] = { damage = 34, name = "CompactRifle"},
    [-1660422300] = { damage = 40, name = "MG"},
    [2144741730] = { damage = 45, name = "CombatMG"},
    [1627465347] = { damage = 34, name = "Gusenberg"},
    [100416529] = { damage = 101, name = "SniperRifle"},
    [205991906] = { damage = 216, name = "HeavySniper"},
    [-952879014] = { damage = 65, name = "MarksmanRifle"},
    [1119849093] = { damage = 30, name = "Minigun"},
    [-1466123874] = { damage = 165, name = "Musket"},
    [911657153] = { damage = 1, name = "StunGun"},
    [1198879012] = { damage = 10, name = "FlareGun"},
    [-598887786] = { damage = 220, name = "MarksmanPistol"},
    [1834241177] = { damage = 30, name = "Railgun"},
    [-275439685] = { damage = 30, name = "DoubleBarrelShotgun"},
    [-1746263880] = { damage = 81, name = "Double Action Revolver"},
    [-2009644972] = { damage = 30, name = "SNS Pistol Mk II"},
    [-879347409] = { damage = 200, name = "Heavy Revolver Mk II"},
    [-1768145561] = { damage = 32, name = "Special Carbine Mk II"},
    [-2066285827] = { damage = 33, name = "Bullpup Rifle Mk II"},
    [1432025498] = { damage = 32, name = "Pump Shotgun Mk II"},
    [1785463520] = { damage = 75, name = "Marksman Rifle Mk II"},
    [961495388] = { damage = 40, name = "Assault Rifle Mk II"},
    [-86904375] = { damage = 33, name = "Carbine Rifle Mk II"},
    [-608341376] = { damage = 47, name = "Combat MG Mk II"},
    [177293209] = { damage = 230, name = "Heavy Sniper Mk II"},
    [-1075685676] = { damage = 32, name = "Pistol Mk II"},
    [2024373456] = { damage = 25, name = "SMG Mk II"}
}

--[Detections]

Config.AntiBlips = false -- Detectiing if player tries to use blips on the server
Config.ClearPedTasksImmediatelyDetection = true -- Detecting if cheater tries to kick other players out of vehicles
Config.AntiExplosionDamage = true -- This prevents players from being killed by Explosions.
Config.AntiGodMode = true -- Detects most of GodMode Cheats and Logs/Bans them.
Config.AntiSpectate = true -- Detects if player enters in spectator mode
Config.AntiRagdoll = false -- Detects No Ragdoll (Do not turn on atm)
Config.AntiInvisible = false -- Detects if the player is Invisible. (Can cause alot of false bans if you are invisible while noclipping and stuff if your permissions are not set.)
Config.AntiRadar = false -- Detects if Radar (Minimap) is visible for players that are not in a car (Use only if you hide the radar from players)
Config.AntiThermalVision = false -- Detects if player is using Thermal Vision.
Config.AntiNightVision = true -- Detects if player is using Night Vision.
Config.AntiTriggerBot = false -- Aimbot and triggerbot (Beta, not recommended to use atm)
Config.AntiPedChange = false -- Detects if Player has changed its ped
Config.AntiFreeCam = false -- Detects if Player is Using Freecam (Do not use with kashacters. esx)
Config.AntiGiveArmor = true -- Detects Give-Armor Cheats
Config.AntiVDM = true -- Vehicle speed detection
Config.SuperJump = true -- Prevents player from using Super-Jump
Config.AntiInfiniteStamina = false -- Detects if player is using infinite stamina
Config.AntiCheatEngine = true -- Anti Cheat Engine
Config.AntiSpawnObjects = true -- Blacklisted objects detection
Config.AntiSpawnVehicles = false -- Blacklisted vehicle detection
Config.AntiSpawnPeds = false -- Blacklisted ped detection
Config.DeleteBrokenCars = false -- Delete cars that are unable to drive (Broken cars)
Config.AntiTaze = false -- Anti Taze Player (Do not enable if cops or other can have a tazer gun on the server! if not this can detect alot of modders.)
Config.EventsDetect = true -- Detects Events

--[Tables]

Config.AntiBlacklistedKey = true -- This will ban the player if the selected key is pressed multiple times (That means player is opening a executor)
Config.BlacklistedKeys = {121} -- Blacklisted Keys

Config.AntiBlacklistedTasks = true -- Detects BlacklistTask
Config.AntiBlacklistedAnims = true -- Detects BlacklistAnims
Config.AntiBlacklistedWords = true -- Blacklisted words you don't want in the chat

Config.BlacklistedTasks = {100, 101, 151, 221, 222} -- Blacklisted Task
Config.BlacklistedAnims = { -- Format: Anim Dict, Anim Name.
	{"rcmpaparazzo_2", "shag_loop_poppy", "anim@mp_player_intupperfinger", "idle_a_fp"}
}

Config.ExplosionProtection = true
Config.BlockedExplosions = {
    0, -- Grenade
    1, -- GrenadeLauncher
    3, -- Molotov
    4, -- Rocket
    16, -- Ship_Destroy
    19, -- SmokeGrenadeLauncher
    20, -- SmokeGrenade
    22, -- Flare
    25, -- Programmablear
    26, -- Train
    27, -- Barrel
    28, -- PROPANE
    29, -- Blimp
	31,
	32,
    33, -- VehicleBullet
    35, -- FireWork
    36, -- SnowBall
    37, -- ProxMine
    38, -- Valkyrie_Cannon
	40,
	42,
	43,
	44,
	45,
	46,
	47,

}

Config.BlacklistedWeapons = {
    `WEAPON_SNIPERRIFLE`, 
    `WEAPON_HEAVYSNIPER`, 
    `WEAPON_MARKSMANRIFLE`, 
    `WEAPON_MARKSMANRIFLE_MK2`, 
    `WEAPON_RPG`, 
    `WEAPON_GRENADELAUNCHER`, 
    `WEAPON_GRENADELAUNCHER_SMOKE`, 
    `WEAPON_MINIGUN`, 
    `WEAPON_FIREWORK`, 
    `WEAPON_RAILGUN`, 
    `WEAPON_HOMINGLAUNCHER`, 
    `WEAPON_COMPACTLAUNCHER`, 
    `WEAPON_RAYMINIGUN`, 
    `WEAPON_GRENADE`, 
    `WEAPON_BZGAS`, 
    `WEAPON_STICKYBOMB`, 
    `WEAPON_PROXMINE`, 
    `WEAPON_PIPEBOMB`, 
    `WEAPON_SMOKEGRENADE`, 
    `WEAPON_ROCKET`, 
    `WEAPON_EXPLOSION`,
    `WEAPON_FLARE`,
    `WEAPON_STINGER`,
    `WEAPON_MUSKET`
}

Config.BlacklistedVehicles = { -- Models/Vehicles/Airplanes etc etc.
    `cargoplane`,
	`cerberus`,
	`cerberus2`,
	`cerberus3`,
	`hauler2`,
	`phantom2`,
	`terbyte`,
	`issi4`,
	`issi5`,
    `issi6`,
	`akula`,
	`annihilator`,
	`buzzard`,
	`hunter`,
	`savage`,
	`apc`,
	`barrage`,
	`chernobog`,
	`halftVCACk`,
	`khanjali`,
	`minitank`,
	`rhino`,
	`scarab`,
	`scarab2`,
	`scarab3`,
	`thruster`,
	`trailersmall2`,
	`oppressor`,
	`oppressor2`,
	`dominator4`,
	`dominator5`,
	`dominator6`,
	`dukes2`,
	`impaler2`,
	`impaler3`,
	`impaler4`,
	`imperator`,
	`imperator2`,
	`imperator3`,
	`bruiser`,
	`bruiser2`,
	`bruiser3`,
	`brutus`,
	`brutus2`,
	`brutus3`,
	`caVCACara`,
	`dune4`,
	`dune5`,
	`insurgent`,
	`insurgent3`,
	`menacer`,
	`nightshark`,
	`technical`,
	`technical2`,
	`technical3`,
	`zhaba`,
	`avenger`,
	`avenger2`,
	`besra`,
	`jet`,
	`hydra`,
	`strikeforce`,
	`titan`,
	`volatol`,
	`limo2`,
	`zr380`,
	`zr3802`,
	`zr3803`,
	`deluxo`,
	`vigilante`,
	`boxville5`,
	`kuruma2`,
	`scramjet`,
	`rcmpaparazzo_2`,
}

Config.BlacklistedPeds = { -- Peds, animals, etc.
    `a_m_m_acult_01`,
    `a_m_y_acult_02`,
    `a_m_o_acult_01`,
    `a_m_y_acult_01`,
    `u_m_y_juggernaut_01`,
    `u_f_m_drowned_01`,
    `s_m_y_swat_01`,
    `a_c_sharktiger`,
    `a_c_chimp`,
    `a_c_humpback`,
    `a_c_rhesus`,
    `u_m_y_zombie_01`,
    `ig_wade`,
    `s_m_m_paramedic_01`,
    `s_m_y_fireman_01`,
    `s_m_y_fireman_01`,
    `mp_f_freemode_01`,
    `s_f_y_bartender_01`,
    `a_m_y_beachvesp_01`,
    `a_m_y_beach_03`,
    `a_m_y_beach_02`,
    `a_m_m_beach_02`,
    `a_m_y_beach_01`,
    `s_m_y_baywatch_01`,
    `mp_f_boatstaff_01`,
    `u_m_m_bikehire_01`,
    `a_f_y_bevhills_04`,
    `s_m_m_bouncer_01`,
    `s_m_y_armymech_01`,
    `s_m_y_autopsy_01`,
    `s_m_y_blackops_01`,
    `s_m_y_blackops_02`,
    `rcmpaparazzo_2`,
    `u_m_y_abner`
}

Config.BlacklistedCommands = {
    "chocolate",
	"pk",
    "haha",
    "Fucked",
	"injected",
	"lol",
	"vRP",
	"deleted due to u being a nigger",
	"panickey",
	"killmenu",
	"Dopamine injected successfully",
    "parent menu doesn",
    "www.d0pamine.xyz",
    "d0pamine v1.1 by Nertigel",
	"d0pamine",
	"lynx",
	"brutan",
	"panic",
	"FOriv gay",
	"TiagoModz#1478",
	"WarMenu",
	"tiago",
	"TiagoModz",
	"dopamine",
	"dopamina",
	"Nertigel: This server is protected and the menu is not gonna work here.", 
	"Information",
	"[dopamine]",
	"KP",
	"opk",
	"jolmany",
	"FunCtionOk",
	"hile",
	"hack",
	"cheat",
	"cheating",
	"cheat injected",
	"Fuckckfivemdownloadhacks",
	"inject",
	"lua",
	".lua",
	"panik",
    "h:xd",
    "Desudo",
    "Brutan",
    "EulenCheats",
    "Lynx 8",
    "www.lynxmenu.com",
    "HamHaxia",
    "Ham Mafia",
    "www.renalua.com",
    "Fallen#0811",
    "Fallout",
    "Fallout.lua",
    "Falloutmenu",
    "redEngine",
    "executor",
    "//",
    "Rena",
    "HamHaxia", 
    "Ham Mafia", 
    "Xanax#0134", 
    ">:D Player Crash",  
    "34ByTe Community", 
    "lynxmenu.com", 
    "Anti-Lynx",
    "Baran",
    "iLostName#7138",
    "Melon#1379",
    "hammafia.com",
    "AlphaV ~ 5391",
    "vjuton.pl",
    "Soviet Bear",
    "MARVIN menu",
    "KoGuSzEk#3251",
    "satan",
    "Fallen",
    "ribbon",
    "ribbon_1",
    "яιввση#6666",
    "noyaas#2545",
    "Created by noyaas#2545",
    "Authentication was successful",
    "AlienMenu",
    "Alien Menu"
}	

Config.BlacklistWords = {
    "Esx_TEAM",
    "EsxTeam",
    "AlienMenu",
    "Alien Menu",
    "Desudo",
    "Brutan",
    "EulenCheats",
    "Lynx 8",
    "www.lynxmenu.com",
    "HamHaxia",
    "Ham Mafia",
    "www.renalua.com",
    "Fallen#0811",
    "Rena",
    "HamHaxia", 
    "Ham Mafia", 
    "Xanax#0134", 
    ">:D Player Crash",  
    "34ByTe Community", 
    "lynxmenu.com", 
    "Anti-Lynx",
    "Baran#8992",
    "iLostName#7138",
    "85.190.90.118",
    "Melon#1379",
    "hammafia.com",
    "AlphaV ~ 5391",
    "vjuton.pl",
    "Soviet Bear",
    "MARVIN menu",
    "KoGuSzEk#3251",
    "devtoolOpening",
    "localhost"
}

Config.Events = {
    "m3:admin:server:goto",
    "m3:admin:server:bring",
    "m3:admin:server:setGps",
    "m3:admin:server:clearInv",
    "m3:admin:server:openInv",
    "m3:admin:server:heal",
    "m3:admin:server:revive",
    "m3:admin:server:setGps",
    "m3:admin:server:toggleFreeze",
    "m3:admin:server:kill",
    "m3:admin:server:privateMessage",
    "m3:admin:server:kick",
    "m3:admin:server:ban",
    "m3:admin:server:giveItem",
    "m3:admin:server:giveVehicle",
    "m3:admin:server:giveMoney",
    "m3:admin:server:giveWeapon",
    "m3:admin:server:skin",
    "m3:admin:server:screenshot",
    "m3:admin:server:wipePlayer",
    "m3:admin:server:selfLog",
    "m3:admin:server:selfRevive",
    "m3:admin:server:selfHeal",
    "m3:admin:server:selfKill",
    "m3:admin:server:toggleNoclip",
    "m3:admin:server:toggleSelfFreeze",
    "m3:admin:server:announce",
    "m3:admin:server:clearArea",
    "m3:admin:server:allKick",
    "m3:admin:server:allBring",
    "m3:admin:server:reviveAll",
    "m3:admin:server:changeTime",
    "m3:admin:server:freezeTime",
    "m3:admin:server:unfreezeTime",
    "m3:admin:server:changeWeather",
    "m3:admin:server:requestAllSync",
    "m3:admin:server:refreshBanlist",
    "m3:admin:server:getPlayers",
    "m3:admin:server:getTargetCoord",
    "m3:admin:server:playerSpawned",
    "m3:admin:client:loadPermissions",
    "m3:admin:client:setCoord",
    "m3:admin:client:kill",
    "m3:admin:client:setGps",
    "m3:admin:client:clearArea",
    "m3:admin:client:spawnVehicle",
    "esx_vehicleshop:isPlateTaken",
    "m3:admin:client:updateWeather",
    "utx-taco:ekmekver",
    "esx_mafiajob:confiscatePlayerItem",
    "vrp_slotmachine:server:2",
    "Banca:deposit",
    "esx_vehicletrunk:giveDirty",
    "gambling:spend",
    "AdminMenu:giveDirtyMoney",
    --"truckerJob:success",
    --"esx_ambulancejob:revive",
    --"DiscordBot:playerDied",
    "hentailover:xdlol",
    "antilynx8:anticheat",
    "antilynxr6:detection",
    "esx_society:getOnlinePlayers",
    --"_chat:messageEntered",
    "antilynx8r4a:anticheat",
    "antilynxr4:detect",
    "js:jailuser", 
    "ynx8:anticheat",
    "lynx8:anticheat",
    "adminmenu:allowall",
    "h:xd",
    --"esx-qalle-jail:jailPlayer",
    "adminmenu:setsalary",
    "adminmenu:cashoutall",
    --"paycheck:salary",
    "HCheat:TempDisableDetection",
    "esx_drugs:pickedUpCannabis",
    "esx_drugs:processCannabis",
    "esx-qalle-hunting:reward",
    "esx-qalle-hunting:sell",
    "esx_mecanojob:onNPCJobCompleted",
    "BsCuff:Cuff696999",
    "veh_SR:CheckMoneyForVeh",
    "esx_carthief:alertcops",
    "mellotrainer:adminTempBan",
    "mellotrainer:adminKick",
    "esx_society:putVehicleInGarage",
    "kashactersS:DeleteCharacter",
	"esx:clientLog",
	'esx_drugs:startHarvestCoke',
    'esx_drugs:stoopHarvestCoke',
    'esx_drugs:startTransformCoke',
    'esx_drugs:stopTransformCoke',
    'esx_drugs:startSellCoke',
    'esx_drugs:stopSellCoke',
    'esx_drugs:startHarvestMeth',
    'esx_drugs:stoopHarvestMeth',
    'esx_drugs:startTransformMeth',
    'esx_drugs:stopTransformMeth',
    'esx_drugs:startSellMeth',
    'esx_drugs:stopSellMeth',
    'esx_drugs:startHarvestWeed',
    'esx_drugs:stoopHarvestWeed',
    'esx_drugs:startTransformWeed',
    'esx_drugs:stopTransformWeed',
    'esx_drugs:startSellWeed',
    'esx_drugs:stopSellWeed',
    'esx_drugs:startHarvestOpium',
    'esx_drugs:stopHarvestOpium',
    'esx_drugs:startTransformOpium',
    'esx_drugs:stopTransformOpium',
    'esx_drugs:startSellOpium',
    'esx_drugs:stopSellOpium',
    "gcPhone:_internalAddMessageLRAC",
    "gcPhone:tchat_channelLRAC",
    "gcPhone:twitter_postTweets",
    "esx_communityservice:sendToCommunityService",
    "esx_vehicleshop:setVehicleOwnedLRAC",
    "esx_mafiajob:confiscateLRACPlayerItem",
    "vrp_slotmachLRACine:server:2",
    "Banca:dLRACeposit",
    "bank:depLRACositt",
    "esx_jobs:caLRACution", "give_back",
    "esx_fueldLRACelivery:pay",
    "esx_carthLRACief:pay",
    "esx_godiLRACrtyjob:pay",
    "esx_pizza:pLRACay",
    "esx_ranger:pLRACay",
    "esx_garbageLRACjob:pay",
    "esx_truckLRACerjob:pay",
    "AdminMeLRACnu:giveBank",
    "AdminMLRACenu:giveCash",
    "esx_goLRACpostaljob:pay",
    "esx_baLRACnksecurity:pay",
    "esx_sloLRACtmachine:sv:2",
    "esx:giLRACveInventoryItem",
    "NB:recLRACruterplayer",
    "esx_biLRAClling:sendBill",
    "esx_jailer:sendToJail",
    "esx_jaLRACil:sendToJail",
    "js:jaLRACiluser",
    --"esx-qalle-jail:jailyer",
    "esx_dmvschool:pLRACay", 
    "LegacyFuel:PayFuLRACel",
    "OG_cuffs:cuffCheckNeLRACarest",
    "cuffSeLRACrver",
    "cuffGLRACranted",
    "police:cuffGLRACranted",
    "esx_handcuffs:cufLRACfing",
    "esx_policejob:haLRACndcuff",
    "bank:withdLRACraw",
    "dmv:succeLRACss",
    "esx_skin:responseSaLRACveSkin",
    "esx_dmvschool:addLiceLRACnse",
    "esx_mechanicjob:starLRACtCraft",
    "esx_drugs:startHarvestWLRACeed",
    "esx_drugs:startTransfoLRACrmWeed",
    "esx_drugs:startSellWeLRACed",
    "esx_drugs:startHarvestLRACCoke",
    "esx_drugs:startTransLRACformCoke",
    "esx_drugs:startSellCLRACoke",
    "esx_drugs:startHarLRACvestMeth",
    "esx_drugs:startTLRACransformMeth",
    "esx_drugs:startSellMLRACeth",
    "esx_drugs:startHLRACarvestOpium",
    "esx_drugs:startSellLRACOpium",
    "esx_drugs:starLRACtTransformOpium",
    "esx_blanchisLRACseur:startWhitening",
    "esx_drugs:stopHarvLRACestCoke",
    "esx_drugs:stopTranLRACsformCoke",
    "esx_drugs:stopSellLRACCoke",
    "esx_drugs:stopHarvesLRACtMeth",
    "esx_drugs:stopTranLRACsformMeth",
    "esx_drugs:stopSellMLRACeth",
    "esx_drugs:stopHarLRACvestWeed",
    "esx_drugs:stopTLRACransformWeed",
    "esx_drugs:stopSellWLRACeed",
    "esx_drugs:stopHarvestLRACOpium",
    "esx_drugs:stopTransLRACformOpium",
    "esx_drugs:stopSellOpiuLRACm",
    "esx_society:openBosLRACsMenu",
    "esx_jobs:caLRACution",
    "esx_tankerjob:LRACpay",
    "esx_vehicletrunk:givLRACeDirty",
    "gambling:speLRACnd",
    "AdminMenu:giveDirtyMLRAConey",
    "esx_moneywash:depoLRACsit",
    "esx_moneywash:witLRAChdraw",
    "mission:completLRACed",
    "99kr-burglary:addMLRAConey",
    "hentailover:xdlol",
    "antiLRAC8:anticheat",
    "antiLRACr6:detection",
    "esx:getShLRACaredObjLRACect",
    "esx_society:getOnlLRACinePlayers",
    "antiLRAC8r4a:anticheat",
    "antiLRACr4:detect",
    "js:jaLRACiluser", 
    "ynx8:anticheat",
    "LRAC8:anticheat",
    "adminmenu:allowall",
    "adminmenu:setsalary",
    "adminmenu:cashoutall",
    "bank:tranLRACsfer",
    "paycheck:bonLRACus",
    "paycheck:salLRACary",
    "HCheat:TempDisableDetLRACection",
    "esx_drugs:pickedUpCLRACannabis",
    "esx_drugs:processCLRACannabis",
    "esx-qalle-hunting:LRACreward",
    "esx-qalle-hunting:seLRACll",
    "esx_mecanojob:onNPCJobCLRACompleted",
    "BsCuff:Cuff696LRAC999",
    "veh_SR:CheckMonLRACeyForVeh",
    "esx_carthief:alertcoLRACps",
    "mellotrainer:adminTeLRACmpBan",
    "mellotrainer:adminKickLRAC",
    "antilynx8:anticheat",
    "mellotrainer:adminKick",
    "Tem2LPs5Para5dCyjuHm87y2catFkMpV",
    "dqd36JWLRC72k8FDttZ5adUKwvwq9n9m",
    "antilynx8:anticheat",
    "antilynxr4:detect",
    "antilynxr6:detection",
    "ynx8:anticheat",
    "antilynx8r4a:anticheat",
    "lynx8:anticheat",
    "AntiLynxR4:kick",
    "AntiLynxR4:log",
    "CRPEngine:Server:AddItem",
    "kaves_base:removeItem",
    "chat:server:ServerPSA",
    "lester:vendita",
    "gcPhone:yellow_postIlan",
    "esx-qalle-sellvehicles:buyVehicle",
    "99kr-shops:Cashier",
    "esx_vangelico_robbery:gioielli",
    "esx_vangelico_robbery:gioielli1",
    "esx-ecobottles:retrieveBottle",
    "esx-ecobottles:sellBottles",
    "loffe_carthief:questFinished",
    "loffe_fishing:caught",
    "loffe_fishing:sell",
    "esx_loffe_fangelse:Pay",
    "loffe_robbery:pickUp",
    "cylex:startSellSarap",
    "cylex:startTransformSarap",
    "cylex:startHarvestSarap",
    "cylex:startSellMelon",
    "cylex:startTransformMelon",
    "cylex:startHarvestMelon",
    "lh-bankrobbery:server:recieveItem",
    "hospital:client:Revive",
    "sp_admin:menuv",
    "sp_admin:giveCash",
    "sp_admin:giveDirtyMoney",
    "sp_admin:giveCash"
}

Config.Objects = {
    [GetHashKey("prop_gas_tank_01a")] = true,
    [GetHashKey("prop_gascyl_01a")] = true,
    [GetHashKey("prop_cs_dildo_01")] = true,
    [GetHashKey("prop_ld_toilet_01")] = true,
    [GetHashKey("prop_ld_bomb_anim")] = true,
    [GetHashKey("prop_ld_farm_couch01")] = true,
	[GetHashKey("hei_prop_carrier_radar_1_l1")] = true,
	[GetHashKey("v_res_mexball")] = true,
	[GetHashKey("prop_rock_1_a")] = true,
	[GetHashKey("prop_rock_1_b")] = true,
	[GetHashKey("prop_rock_1_c")] = true,
	[GetHashKey("prop_rock_1_d")] = true,
	[GetHashKey("prop_player_gasmask")] = true,
	[GetHashKey("prop_rock_1_e")] = true,
	[GetHashKey("prop_rock_1_f")] = true,
	[GetHashKey("prop_rock_1_g")] = true,
	[GetHashKey("prop_rock_1_h")] = true,
	[GetHashKey("prop_test_boulder_01")] = true,
	[GetHashKey("prop_test_boulder_02")] = true,
	[GetHashKey("prop_test_boulder_03")] = true,
	[GetHashKey("prop_test_boulder_04")] = true,
	[GetHashKey("apa_mp_apa_crashed_usaf_01a")] = true,
	[GetHashKey("ex_prop_exec_crashdp")] = true,
	[GetHashKey("apa_mp_apa_yacht_o1_rail_a")] = true,
	[GetHashKey("apa_mp_apa_yacht_o1_rail_b")] = true,
	[GetHashKey("apa_mp_h_yacht_armchair_01")] = true,
	[GetHashKey("apa_mp_h_yacht_armchair_03")] = true,
	[GetHashKey("apa_mp_h_yacht_armchair_04")] = true,
	[GetHashKey("apa_mp_h_yacht_barstool_01")] = true,
	[GetHashKey("apa_mp_h_yacht_bed_01")] = true,
	[GetHashKey("apa_mp_h_yacht_bed_02")] = true,
	[GetHashKey("apa_mp_h_yacht_coffee_table_01")] = true,
	[GetHashKey("apa_mp_h_yacht_coffee_table_02")] = true,
	[GetHashKey("apa_mp_h_yacht_floor_lamp_01")] = true,
	[GetHashKey("apa_mp_h_yacht_side_table_01")] = true,
	[GetHashKey("apa_mp_h_yacht_side_table_02")] = true,
	[GetHashKey("apa_mp_h_yacht_sofa_01")] = true,
	[GetHashKey("apa_mp_h_yacht_sofa_02")] = true,
	[GetHashKey("apa_mp_h_yacht_stool_01")] = true,
	[GetHashKey("apa_mp_h_yacht_strip_chair_01")] = true,
	[GetHashKey("apa_mp_h_yacht_table_lamp_01")] = true,
	[GetHashKey("apa_mp_h_yacht_table_lamp_02")] = true,
	[GetHashKey("apa_mp_h_yacht_table_lamp_03")] = true,
	[GetHashKey("prop_flag_columbia")] = true,
	[GetHashKey("apa_mp_apa_yacht_o2_rail_a")] = true,
	[GetHashKey("apa_mp_apa_yacht_o2_rail_b")] = true,
	[GetHashKey("apa_mp_apa_yacht_o3_rail_a")] = true,
	[GetHashKey("apa_mp_apa_yacht_o3_rail_b")] = true,
	[GetHashKey("apa_mp_apa_yacht_option1")] = true,
	[GetHashKey("proc_searock_01")] = true,
	[GetHashKey("apa_mp_h_yacht_")] = true,
	[GetHashKey("apa_mp_apa_yacht_option1_cola")] = true,
	[GetHashKey("apa_mp_apa_yacht_option2")] = true,
	[GetHashKey("apa_mp_apa_yacht_option2_cola")] = true,
	[GetHashKey("apa_mp_apa_yacht_option2_colb")] = true,
	[GetHashKey("apa_mp_apa_yacht_option3")] = true,
	[GetHashKey("apa_mp_apa_yacht_option3_cola")] = true,
	[GetHashKey("apa_mp_apa_yacht_option3_colb")] = true,
	[GetHashKey("apa_mp_apa_yacht_option3_colc")] = true,
	[GetHashKey("apa_mp_apa_yacht_option3_cold")] = true,
	[GetHashKey("apa_mp_apa_yacht_option3_cole")] = true,
	[GetHashKey("apa_mp_apa_yacht_jacuzzi_cam")] = true,
	[GetHashKey("apa_mp_apa_yacht_jacuzzi_ripple003")] = true,
	[GetHashKey("apa_mp_apa_yacht_jacuzzi_ripple1")] = true,
	[GetHashKey("apa_mp_apa_yacht_jacuzzi_ripple2")] = true,
	[GetHashKey("apa_mp_apa_yacht_radar_01a")] = true,
	[GetHashKey("apa_mp_apa_yacht_win")] = true,
	[GetHashKey("prop_crashed_heli")] = true,
	[GetHashKey("apa_mp_apa_yacht_door")] = true,
	[GetHashKey("prop_shamal_crash")] = true,
	[GetHashKey("xm_prop_x17_shamal_crash")] = true,
	[GetHashKey("apa_mp_apa_yacht_door2")] = true,
	[GetHashKey("apa_mp_apa_yacht")] = true,
	[GetHashKey("prop_flagpole_2b")] = true,
	[GetHashKey("prop_flagpole_2c")] = true,
	[GetHashKey("prop_flag_canada")] = true,
	[GetHashKey("apa_prop_yacht_float_1a")] = true,
	[GetHashKey("apa_prop_yacht_float_1b")] = true,
	[GetHashKey("apa_prop_yacht_glass_01")] = true,
	[GetHashKey("apa_prop_yacht_glass_02")] = true,
	[GetHashKey("apa_prop_yacht_glass_03")] = true,
	[GetHashKey("apa_prop_yacht_glass_04")] = true,
	[GetHashKey("apa_prop_yacht_glass_05")] = true,
	[GetHashKey("apa_prop_yacht_glass_06")] = true,
	[GetHashKey("apa_prop_yacht_glass_07")] = true,
	[GetHashKey("apa_prop_yacht_glass_08")] = true,
	[GetHashKey("apa_prop_yacht_glass_09")] = true,
	[GetHashKey("apa_prop_yacht_glass_10")] = true,
	[GetHashKey("prop_flag_canada_s")] = true,
	[GetHashKey("prop_flag_eu")] = true,
	[GetHashKey("prop_flag_eu_s")] = true,
	[GetHashKey("prop_target_blue_arrow")] = true,
	[GetHashKey("prop_target_orange_arrow")] = true,
	[GetHashKey("prop_target_purp_arrow")] = true,
	[GetHashKey("prop_target_red_arrow")] = true,
	[GetHashKey("apa_prop_flag_argentina")] = true,
	[GetHashKey("apa_prop_flag_australia")] = true,
	[GetHashKey("apa_prop_flag_austria")] = true,
	[GetHashKey("apa_prop_flag_belgium")] = true,
	[GetHashKey("apa_prop_flag_brazil")] = true,
	[GetHashKey("apa_prop_flag_canadat_yt")] = true,
	[GetHashKey("apa_prop_flag_china")] = true,
	[GetHashKey("apa_prop_flag_columbia")] = true,
	[GetHashKey("apa_prop_flag_croatia")] = true,
	[GetHashKey("apa_prop_flag_czechrep")] = true,
	[GetHashKey("apa_prop_flag_denmark")] = true,
	[GetHashKey("apa_prop_flag_england")] = true,
	[GetHashKey("apa_prop_flag_eu_yt")] = true,
	[GetHashKey("apa_prop_flag_finland")] = true,
	[GetHashKey("apa_prop_flag_france")] = true,
	[GetHashKey("apa_prop_flag_german_yt")] = true,
	[GetHashKey("apa_prop_flag_hungary")] = true,
	[GetHashKey("apa_prop_flag_ireland")] = true,
	[GetHashKey("apa_prop_flag_israel")] = true,
	[GetHashKey("apa_prop_flag_italy")] = true,
	[GetHashKey("apa_prop_flag_jamaica")] = true,
	[GetHashKey("apa_prop_flag_japan_yt")] = true,
	[GetHashKey("apa_prop_flag_canada_yt")] = true,
	[GetHashKey("apa_prop_flag_lstein")] = true,
	[GetHashKey("apa_prop_flag_malta")] = true,
	[GetHashKey("apa_prop_flag_mexico_yt")] = true,
	[GetHashKey("apa_prop_flag_netherlands")] = true,
	[GetHashKey("apa_prop_flag_newzealand")] = true,
	[GetHashKey("apa_prop_flag_nigeria")] = true,
	[GetHashKey("apa_prop_flag_norway")] = true,
	[GetHashKey("apa_prop_flag_palestine")] = true,
	[GetHashKey("apa_prop_flag_poland")] = true,
	[GetHashKey("apa_prop_flag_portugal")] = true,
	[GetHashKey("apa_prop_flag_puertorico")] = true,
	[GetHashKey("apa_prop_flag_russia_yt")] = true,
	[GetHashKey("apa_prop_flag_scotland_yt")] = true,
	[GetHashKey("apa_prop_flag_script")] = true,
	[GetHashKey("apa_prop_flag_slovakia")] = true,
	[GetHashKey("apa_prop_flag_slovenia")] = true,
	[GetHashKey("apa_prop_flag_southafrica")] = true,
	[GetHashKey("apa_prop_flag_southkorea")] = true,
	[GetHashKey("apa_prop_flag_spain")] = true,
	[GetHashKey("apa_prop_flag_sweden")] = true,
	[GetHashKey("apa_prop_flag_switzerland")] = true,
	[GetHashKey("apa_prop_flag_turkey")] = true,
	[GetHashKey("apa_prop_flag_uk_yt")] = true,
	[GetHashKey("apa_prop_flag_us_yt")] = true,
	[GetHashKey("apa_prop_flag_wales")] = true,
	[GetHashKey("prop_flag_uk")] = true,
	[GetHashKey("prop_flag_uk_s")] = true,
	[GetHashKey("prop_flag_us")] = true,
	[GetHashKey("prop_flag_usboat")] = true,
	[GetHashKey("prop_flag_us_r")] = true,
	[GetHashKey("prop_flag_us_s")] = true,
	[GetHashKey("prop_flag_france")] = true,
	[GetHashKey("prop_flag_france_s")] = true,
	[GetHashKey("prop_flag_german")] = true,
	[GetHashKey("prop_flag_german_s")] = true,
	[GetHashKey("prop_flag_ireland")] = true,
	[GetHashKey("prop_flag_ireland_s")] = true,
	[GetHashKey("prop_flag_japan")] = true,
	[GetHashKey("prop_flag_japan_s")] = true,
	[GetHashKey("prop_flag_ls")] = true,
	[GetHashKey("prop_flag_lsfd")] = true,
	[GetHashKey("prop_flag_lsfd_s")] = true,
	[GetHashKey("prop_flag_lsservices")] = true,
	[GetHashKey("prop_flag_lsservices_s")] = true,
	[GetHashKey("prop_flag_ls_s")] = true,
	[GetHashKey("prop_flag_mexico")] = true,
	[GetHashKey("prop_flag_mexico_s")] = true,
	[GetHashKey("prop_flag_russia")] = true,
	[GetHashKey("prop_flag_russia_s")] = true,
	[GetHashKey("prop_flag_s")] = true,
	[GetHashKey("prop_flag_sa")] = true,
	[GetHashKey("prop_flag_sapd")] = true,
	[GetHashKey("prop_flag_sapd_s")] = true,
	[GetHashKey("prop_flag_sa_s")] = true,
	[GetHashKey("prop_flag_scotland")] = true,
	[GetHashKey("prop_flag_scotland_s")] = true,
	[GetHashKey("prop_flag_sheriff")] = true,
	[GetHashKey("prop_flag_sheriff_s")] = true,
	[GetHashKey("prop_flag_uk")] = true,
	[GetHashKey("prop_flag_uk_s")] = true,
	[GetHashKey("prop_flag_us")] = true,
	[GetHashKey("prop_flag_usboat")] = true,
	[GetHashKey("prop_flag_us_r")] = true,
	[GetHashKey("prop_flag_us_s")] = true,
	[GetHashKey("prop_flamingo")] = true,
	[GetHashKey("prop_swiss_ball_01")] = true,
	[GetHashKey("prop_air_bigradar_l1")] = true,
	[GetHashKey("prop_air_bigradar_l2")] = true,
	[GetHashKey("prop_air_bigradar_slod")] = true,
	[GetHashKey("p_fib_rubble_s")] = true,
	[GetHashKey("prop_money_bag_01")] = true,
	[GetHashKey("p_cs_mp_jet_01_s")] = true,
	[GetHashKey("prop_poly_bag_money")] = true,
	[GetHashKey("prop_air_radar_01")] = true,
	[GetHashKey("hei_prop_carrier_radar_1")] = true,
	[GetHashKey("prop_air_bigradar")] = true,
	[GetHashKey("prop_carrier_radar_1_l1")] = true,
	[GetHashKey("prop_asteroid_01")] = true,
	[GetHashKey("prop_xmas_ext")] = true,
	[GetHashKey("p_oil_pjack_01_amo")] = true,
	[GetHashKey("p_oil_pjack_01_s")] = true,
	[GetHashKey("p_oil_pjack_02_amo")] = true,
	[GetHashKey("p_oil_pjack_03_amo")] = true,
	[GetHashKey("p_oil_pjack_02_s")] = true,
	[GetHashKey("p_oil_pjack_03_s")] = true,
	[GetHashKey("prop_aircon_l_03")] = true,
	[GetHashKey("prop_med_jet_01")] = true,
	[GetHashKey("p_med_jet_01_s")] = true,
	[GetHashKey("hei_prop_carrier_jet")] = true,
	[GetHashKey("bkr_prop_biker_bblock_huge_01")] = true,
	[GetHashKey("bkr_prop_biker_bblock_huge_02")] = true,
	[GetHashKey("bkr_prop_biker_bblock_huge_04")] = true,
	[GetHashKey("bkr_prop_biker_bblock_huge_05")] = true,
	[GetHashKey("hei_prop_heist_emp")] = true,
	[GetHashKey("prop_weed_01")] = true,
	[GetHashKey("prop_air_bigradar")] = true,
	[GetHashKey("prop_juicestand")] = true,
	[GetHashKey("prop_lev_des_barge_02")] = true,
	[GetHashKey("hei_prop_carrier_defense_01")] = true,
	[GetHashKey("prop_aircon_m_04")] = true,
	[GetHashKey("prop_mp_ramp_03")] = true,
	[GetHashKey("stt_prop_stunt_track_dwuturn")] = true,
	[GetHashKey("ch3_12_animplane1_lod")] = true,
	[GetHashKey("ch3_12_animplane2_lod")] = true,
	[GetHashKey("hei_prop_hei_pic_pb_plane")] = true,
	[GetHashKey("light_plane_rig")] = true,
	[GetHashKey("prop_cs_plane_int_01")] = true,
	[GetHashKey("prop_dummy_plane")] = true,
	[GetHashKey("prop_mk_plane")] = true,
	[GetHashKey("v_44_planeticket")] = true,
	[GetHashKey("prop_planer_01")] = true,
	[GetHashKey("ch3_03_cliffrocks03b_lod")] = true,
	[GetHashKey("ch3_04_rock_lod_02")] = true,
	[GetHashKey("csx_coastsmalrock_01_")] = true,
	[GetHashKey("csx_coastsmalrock_02_")] = true,
	[GetHashKey("csx_coastsmalrock_03_")] = true,
	[GetHashKey("csx_coastsmalrock_04_")] = true,
	[GetHashKey("mp_player_introck")] = true,
	[GetHashKey("Heist_Yacht")] = true,
	[GetHashKey("csx_coastsmalrock_05_")] = true,
	[GetHashKey("mp_player_int_rock")] = true,
	[GetHashKey("mp_player_introck")] = true,
	[GetHashKey("prop_flagpole_1a")] = true,
	[GetHashKey("prop_flagpole_2a")] = true,
	[GetHashKey("prop_flagpole_3a")] = true,
	[GetHashKey("prop_a4_pile_01")] = true,
	[GetHashKey("cs2_10_sea_rocks_lod")] = true,
	[GetHashKey("cs2_11_sea_marina_xr_rocks_03_lod")] = true,
	[GetHashKey("prop_gold_cont_01")] = true,
	[GetHashKey("prop_hydro_platform")] = true,
	[GetHashKey("ch3_04_viewplatform_slod")] = true,
	[GetHashKey("ch2_03c_rnchstones_lod")] = true,
	[GetHashKey("proc_mntn_stone01")] = true,
	[GetHashKey("prop_beachflag_le")] = true,
	[GetHashKey("proc_mntn_stone02")] = true,
	[GetHashKey("cs2_10_sea_shipwreck_lod")] = true,
	[GetHashKey("des_shipsink_02")] = true,
	[GetHashKey("prop_dock_shippad")] = true,
	[GetHashKey("des_shipsink_03")] = true,
	[GetHashKey("des_shipsink_04")] = true,
	[GetHashKey("prop_mk_flag")] = true,
	[GetHashKey("prop_mk_flag_2")] = true,
	[GetHashKey("proc_mntn_stone03")] = true,
	[GetHashKey("FreeModeMale01")] = true,
	[GetHashKey("rsn_os_specialfloatymetal_n")] = true,
	[GetHashKey("rsn_os_specialfloatymetal")] = true,
	[GetHashKey("cs1_09_sea_ufo")] = true,
	[GetHashKey("rsn_os_specialfloaty2_light2")] = true,
	[GetHashKey("rsn_os_specialfloaty2_light")] = true,
	[GetHashKey("rsn_os_specialfloaty2")] = true,
	[GetHashKey("rsn_os_specialfloatymetal_n")] = true,
	[GetHashKey("rsn_os_specialfloatymetal")] = true,
	[GetHashKey("P_Spinning_Anus_S_Main")] = true,
	[GetHashKey("P_Spinning_Anus_S_Root")] = true,
	[GetHashKey("cs3_08b_rsn_db_aliencover_0001cs3_08b_rsn_db_aliencover_0001_a")] = true,
	[GetHashKey("sc1_04_rnmo_paintoverlaysc1_04_rnmo_paintoverlay_a")] = true,
	[GetHashKey("rnbj_wallsigns_0001")] = true,
	[GetHashKey("proc_sml_stones01")] = true,
	[GetHashKey("proc_sml_stones02")] = true,
	[GetHashKey("maverick")] = true,
	[GetHashKey("Miljet")] = true,
	[GetHashKey("proc_sml_stones03")] = true,
	[GetHashKey("proc_stones_01")] = true,
	[GetHashKey("proc_stones_02")] = true,
	[GetHashKey("proc_stones_03")] = true,
	[GetHashKey("proc_stones_04")] = true,
	[GetHashKey("proc_stones_05")] = true,
	[GetHashKey("proc_stones_06")] = true,
	[GetHashKey("prop_coral_stone_03")] = true,
	[GetHashKey("prop_coral_stone_04")] = true,
	[GetHashKey("prop_gravestones_01a")] = true,
	[GetHashKey("prop_gravestones_02a")] = true,
	[GetHashKey("prop_gravestones_03a")] = true,
	[GetHashKey("prop_gravestones_04a")] = true,
	[GetHashKey("prop_gravestones_05a")] = true,
	[GetHashKey("prop_gravestones_06a")] = true,
	[GetHashKey("prop_gravestones_07a")] = true,
	[GetHashKey("prop_gravestones_08a")] = true,
	[GetHashKey("prop_gravestones_09a")] = true,
	[GetHashKey("prop_gravestones_10a")] = true,
	[GetHashKey("prop_prlg_gravestone_05a_l1")] = true,
	[GetHashKey("prop_prlg_gravestone_06a")] = true,
	[GetHashKey("test_prop_gravestones_04a")] = true,
	[GetHashKey("test_prop_gravestones_05a")] = true,
	[GetHashKey("test_prop_gravestones_07a")] = true,
	[GetHashKey("test_prop_gravestones_08a")] = true,
	[GetHashKey("test_prop_gravestones_09a")] = true,
	[GetHashKey("prop_prlg_gravestone_01a")] = true,
	[GetHashKey("prop_prlg_gravestone_02a")] = true,
	[GetHashKey("prop_prlg_gravestone_03a")] = true,
	[GetHashKey("prop_prlg_gravestone_04a")] = true,
	[GetHashKey("prop_stoneshroom1")] = true,
	[GetHashKey("prop_stoneshroom2")] = true,
	[GetHashKey("v_res_fa_stones01")] = true,
	[GetHashKey("test_prop_gravestones_01a")] = true,
	[GetHashKey("test_prop_gravestones_02a")] = true,
	[GetHashKey("prop_prlg_gravestone_05a")] = true,
	[GetHashKey("FreemodeFemale01")] = true,
	[GetHashKey("p_cablecar_s")] = true,
	[GetHashKey("stt_prop_stunt_tube_l")] = true,
	[GetHashKey("stt_prop_stunt_track_dwuturn")] = true,
	[GetHashKey("p_spinning_anus_s")] = true,
	[GetHashKey("prop_windmill_01")] = true,
	[GetHashKey("hei_prop_heist_tug")] = true,
	[GetHashKey("prop_air_bigradar")] = true,
	[GetHashKey("p_oil_slick_01")] = true,
	[GetHashKey("prop_dummy_01")] = true,
	[GetHashKey("hei_prop_heist_emp")] = true,
	[GetHashKey("p_tram_cash_s")] = true,
	[GetHashKey("hw1_blimp_ce2")] = true,
	[GetHashKey("prop_fire_exting_1a")] = true,
	[GetHashKey("prop_fire_exting_1b")] = true,
	[GetHashKey("prop_fire_exting_2a")] = true,
	[GetHashKey("prop_fire_exting_3a")] = true,
	[GetHashKey("hw1_blimp_ce2_lod")] = true,
	[GetHashKey("hw1_blimp_ce_lod")] = true,
	[GetHashKey("hw1_blimp_cpr003")] = true,
	[GetHashKey("hw1_blimp_cpr_null")] = true,
	[GetHashKey("hw1_blimp_cpr_null2")] = true,
	[GetHashKey("prop_lev_des_barage_02")] = true,
	[GetHashKey("hei_prop_carrier_defense_01")] = true,
	[GetHashKey("prop_juicestand")] = true,
	[GetHashKey("S_M_M_MovAlien_01")] = true,
	[GetHashKey("s_m_m_movalien_01")] = true,
	[GetHashKey("s_m_m_movallien_01")] = true,
	[GetHashKey("u_m_y_babyd")] = true,
	[GetHashKey("CS_Orleans")] = true,
	[GetHashKey("A_M_Y_ACult_01")] = true,
	[GetHashKey("S_M_M_MovSpace_01")] = true,
	[GetHashKey("U_M_Y_Zombie_01")] = true,
	[GetHashKey("s_m_y_blackops_01")] = true,
	[GetHashKey("a_f_y_topless_01")] = true,
	[GetHashKey("a_c_boar")] = true,
	[GetHashKey("a_c_cat_01")] = true,
	[GetHashKey("a_c_chickenhawk")] = true,
	[GetHashKey("a_c_chimp")] = true,
	[GetHashKey("s_f_y_hooker_03")] = true,
	[GetHashKey("a_c_chop")] = true,
	[GetHashKey("a_c_cormorant")] = true,
	[GetHashKey("a_c_cow")] = true,
	[GetHashKey("a_c_coyote")] = true,
	[GetHashKey("v_ilev_found_cranebucket")] = true,
	[GetHashKey("p_cs_sub_hook_01_s")] = true,
	[GetHashKey("a_c_crow")] = true,
	[GetHashKey("a_c_dolphin")] = true,
	[GetHashKey("a_c_fish")] = true,
	[GetHashKey("hei_prop_heist_hook_01")] = true,
	[GetHashKey("prop_rope_hook_01")] = true,
	[GetHashKey("prop_sub_crane_hook")] = true,
	[GetHashKey("s_f_y_hooker_01")] = true,
	[GetHashKey("prop_vehicle_hook")] = true,
	[GetHashKey("prop_v_hook_s")] = true,
	[GetHashKey("prop_dock_crane_02_hook")] = true,
	[GetHashKey("prop_winch_hook_long")] = true,
	[GetHashKey("a_c_hen")] = true,
	[GetHashKey("a_c_humpback")] = true,
	[GetHashKey("a_c_husky")] = true,
	[GetHashKey("a_c_killerwhale")] = true,
	[GetHashKey("a_c_mtlion")] = true,
	[GetHashKey("a_c_pigeon")] = true,
	[GetHashKey("a_c_poodle")] = true,
	[GetHashKey("prop_coathook_01")] = true,
	[GetHashKey("prop_cs_sub_hook_01")] = true,
	[GetHashKey("a_c_pug")] = true,
	[GetHashKey("a_c_rabbit_01")] = true,
	[GetHashKey("a_c_rat")] = true,
	[GetHashKey("a_c_retriever")] = true,
	[GetHashKey("a_c_rhesus")] = true,
	[GetHashKey("a_c_rottweiler")] = true,
	[GetHashKey("a_c_sharkhammer")] = true,
	[GetHashKey("a_c_sharktiger")] = true,
	[GetHashKey("a_c_shepherd")] = true,
	[GetHashKey("a_c_stingray")] = true,
	[GetHashKey("a_c_westy")] = true,
	[GetHashKey("CS_Orleans")] = true,
	[GetHashKey("prop_windmill_01")] = true,
	[GetHashKey("prop_Ld_ferris_wheel")] = true,
	[GetHashKey("p_tram_crash_s")] = true,
	[GetHashKey("p_oil_slick_01")] = true,
	[GetHashKey("p_ld_stinger_s")] = true,
	[GetHashKey("p_ld_soc_ball_01")] = true,
	[GetHashKey("p_parachute1_s")] = true,
	[GetHashKey("p_cablecar_s")] = true,
	[GetHashKey("prop_beach_fire")] = true,
	[GetHashKey("prop_lev_des_barge_02")] = true,
	[GetHashKey("prop_lev_des_barge_01")] = true,
	[GetHashKey("prop_sculpt_fix")] = true,
	[GetHashKey("prop_flagpole_2b")] = true,
	[GetHashKey("prop_flagpole_2c")] = true,
	[GetHashKey("prop_winch_hook_short")] = true,
	[GetHashKey("prop_flag_canada")] = true,
	[GetHashKey("prop_flag_canada_s")] = true,
	[GetHashKey("prop_flag_eu")] = true,
	[GetHashKey("prop_flag_eu_s")] = true,
	[GetHashKey("prop_flag_france")] = true,
	[GetHashKey("prop_flag_france_s")] = true,
	[GetHashKey("prop_flag_german")] = true,
	[GetHashKey("prop_ld_hook")] = true,
	[GetHashKey("prop_flag_german_s")] = true,
	[GetHashKey("prop_flag_ireland")] = true,
	[GetHashKey("prop_flag_ireland_s")] = true,
	[GetHashKey("prop_flag_japan")] = true,
	[GetHashKey("prop_flag_japan_s")] = true,
	[GetHashKey("prop_flag_ls")] = true,
	[GetHashKey("prop_flag_lsfd")] = true,
	[GetHashKey("prop_flag_lsfd_s")] = true,
	[GetHashKey("prop_cable_hook_01")] = true,
	[GetHashKey("prop_flag_lsservices")] = true,
	[GetHashKey("prop_flag_lsservices_s")] = true,
	[GetHashKey("prop_flag_ls_s")] = true,
	[GetHashKey("prop_flag_mexico")] = true,
	[GetHashKey("prop_flag_mexico_s")] = true,
	[GetHashKey("csx_coastboulder_00")] = true,
	[GetHashKey("des_tankercrash_01")] = true,
	[GetHashKey("des_tankerexplosion_01")] = true,
	[GetHashKey("des_tankerexplosion_02")] = true,
	[GetHashKey("des_trailerparka_02")] = true,
	[GetHashKey("des_trailerparkb_02")] = true,
	[GetHashKey("des_trailerparkc_02")] = true,
	[GetHashKey("des_trailerparkd_02")] = true,
	[GetHashKey("des_traincrash_root2")] = true,
	[GetHashKey("des_traincrash_root3")] = true,
	[GetHashKey("des_traincrash_root4")] = true,
	[GetHashKey("des_traincrash_root5")] = true,
	[GetHashKey("des_finale_vault_end")] = true,
	[GetHashKey("des_finale_vault_root001")] = true,
	[GetHashKey("des_finale_vault_root002")] = true,
	[GetHashKey("des_finale_vault_root003")] = true,
	[GetHashKey("des_finale_vault_root004")] = true,
	[GetHashKey("des_finale_vault_start")] = true,
	[GetHashKey("des_vaultdoor001_root001")] = true,
	[GetHashKey("des_vaultdoor001_root002")] = true,
	[GetHashKey("des_vaultdoor001_root003")] = true,
	[GetHashKey("des_vaultdoor001_root004")] = true,
	[GetHashKey("des_vaultdoor001_root005")] = true,
	[GetHashKey("des_vaultdoor001_root006")] = true,
	[GetHashKey("des_vaultdoor001_skin001")] = true,
	[GetHashKey("des_vaultdoor001_start")] = true,
	[GetHashKey("des_traincrash_root6")] = true,
	[GetHashKey("prop_ld_vault_door")] = true,
	[GetHashKey("prop_vault_door_scene")] = true,
	[GetHashKey("prop_vault_door_scene")] = true,
	[GetHashKey("prop_vault_shutter")] = true,
	[GetHashKey("p_fin_vaultdoor_s")] = true,
	[GetHashKey("v_ilev_bk_vaultdoor")] = true,
	[GetHashKey("prop_gold_vault_fence_l")] = true,
	[GetHashKey("prop_gold_vault_fence_r")] = true,
	[GetHashKey("prop_gold_vault_gate_01")] = true,
	[GetHashKey("prop_bank_vaultdoor")] = true,
	[GetHashKey("des_traincrash_root7")] = true,
	[GetHashKey("prop_flag_russia")] = true,
	[GetHashKey("prop_flag_russia_s")] = true,
	[GetHashKey("prop_flag_s")] = true,
	[GetHashKey("ch2_03c_props_rrlwindmill_lod")] = true,
	[GetHashKey("prop_flag_sa")] = true,
	[GetHashKey("prop_flag_sapd")] = true,
	[GetHashKey("prop_flag_sapd_s")] = true,
	[GetHashKey("prop_flag_sa_s")] = true,
	[GetHashKey("prop_flag_scotland")] = true,
	[GetHashKey("prop_flag_scotland_s")] = true,
	[GetHashKey("prop_flag_sheriff")] = true,
	[GetHashKey("prop_flag_sheriff_s")] = true,
	[GetHashKey("prop_flag_uk")] = true,
	[GetHashKey("prop_yacht_lounger")] = true,
	[GetHashKey("prop_yacht_seat_01")] = true,
	[GetHashKey("prop_yacht_seat_02")] = true,
	[GetHashKey("prop_yacht_seat_03")] = true,
	[GetHashKey("marina_xr_rocks_02")] = true,
	[GetHashKey("marina_xr_rocks_03")] = true,
	[GetHashKey("prop_test_rocks01")] = true,
	[GetHashKey("prop_test_rocks02")] = true,
	[GetHashKey("prop_test_rocks03")] = true,
	[GetHashKey("prop_test_rocks04")] = true,
	[GetHashKey("marina_xr_rocks_04")] = true,
	[GetHashKey("marina_xr_rocks_05")] = true,
	[GetHashKey("marina_xr_rocks_06")] = true,
	[GetHashKey("prop_yacht_table_01")] = true,
	[GetHashKey("csx_searocks_02")] = true,
	[GetHashKey("csx_searocks_03")] = true,
	[GetHashKey("csx_searocks_04")] = true,
	[GetHashKey("csx_searocks_05")] = true,
	[GetHashKey("csx_searocks_06")] = true,
	[GetHashKey("p_yacht_chair_01_s")] = true,
	[GetHashKey("p_yacht_sofa_01_s")] = true,
	[GetHashKey("prop_yacht_table_02")] = true,
	[GetHashKey("csx_coastboulder_00")] = true,
	[GetHashKey("csx_coastboulder_01")] = true,
	[GetHashKey("csx_coastboulder_02")] = true,
	[GetHashKey("csx_coastboulder_03")] = true,
	[GetHashKey("csx_coastboulder_04")] = true,
	[GetHashKey("csx_coastboulder_05")] = true,
	[GetHashKey("csx_coastboulder_06")] = true,
	[GetHashKey("csx_coastboulder_07")] = true,
	[GetHashKey("csx_coastrok1")] = true,
	[GetHashKey("csx_coastrok2")] = true,
	[GetHashKey("csx_coastrok3")] = true,
	[GetHashKey("csx_coastrok4")] = true,
	[GetHashKey("csx_coastsmalrock_01")] = true,
	[GetHashKey("csx_coastsmalrock_02")] = true,
	[GetHashKey("csx_coastsmalrock_03")] = true,
	[GetHashKey("csx_coastsmalrock_04")] = true,
	[GetHashKey("csx_coastsmalrock_05")] = true,
	[GetHashKey("prop_yacht_table_03")] = true,
	[GetHashKey("prop_flag_uk_s")] = true,
	[GetHashKey("prop_flag_us")] = true,
	[GetHashKey("prop_flag_usboat")] = true,
	[GetHashKey("prop_flag_us_r")] = true,
	[GetHashKey("prop_flag_us_s")] = true,
	[GetHashKey("p_gasmask_s")] = true,
	[GetHashKey("prop_flamingo")] = true,
	[GetHashKey("stt_prop_stunt_soccer_ball")] = true,
	[GetHashKey("prop_rock_4_big2")] = true,
	[GetHashKey("p_crahsed_heli_s")] = true,
	[GetHashKey("stt_prop_c4_stack")] = true,
	[GetHashKey("stt_prop_corner_sign_01")] = true,
	[GetHashKey("stt_prop_corner_sign_02")] = true,
	[GetHashKey("stt_prop_corner_sign_03")] = true,
	[GetHashKey("stt_prop_corner_sign_04")] = true,
	[GetHashKey("stt_prop_corner_sign_05")] = true,
	[GetHashKey("stt_prop_corner_sign_06")] = true,
	[GetHashKey("stt_prop_corner_sign_07")] = true,
	[GetHashKey("stt_prop_corner_sign_08")] = true,
	[GetHashKey("stt_prop_corner_sign_09")] = true,
	[GetHashKey("stt_prop_corner_sign_10")] = true,
	[GetHashKey("stt_prop_corner_sign_11")] = true,
	[GetHashKey("stt_prop_corner_sign_12")] = true,
	[GetHashKey("stt_prop_corner_sign_13")] = true,
	[GetHashKey("stt_prop_corner_sign_14")] = true,
	[GetHashKey("stt_prop_flagpole_1a")] = true,
	[GetHashKey("stt_prop_flagpole_1b")] = true,
	[GetHashKey("stt_prop_flagpole_1c")] = true,
	[GetHashKey("stt_prop_flagpole_1d")] = true,
	[GetHashKey("stt_prop_flagpole_1e")] = true,
	[GetHashKey("stt_prop_flagpole_1f")] = true,
	[GetHashKey("stt_prop_flagpole_2a")] = true,
	[GetHashKey("stt_prop_flagpole_2b")] = true,
	[GetHashKey("stt_prop_flagpole_2c")] = true,
	[GetHashKey("stt_prop_flagpole_2d")] = true,
	[GetHashKey("stt_prop_flagpole_2e")] = true,
	[GetHashKey("stt_prop_flagpole_2f")] = true,
	[GetHashKey("stt_prop_hoop_constraction_01a")] = true,
	[GetHashKey("stt_prop_hoop_small_01")] = true,
	[GetHashKey("stt_prop_hoop_tyre_01a")] = true,
	[GetHashKey("stt_prop_lives_bottle")] = true,
	[GetHashKey("stt_prop_race_gantry_01")] = true,
	[GetHashKey("stt_prop_race_start_line_01")] = true,
	[GetHashKey("stt_prop_race_start_line_01b")] = true,
	[GetHashKey("stt_prop_race_start_line_02")] = true,
	[GetHashKey("stt_prop_race_start_line_02b")] = true,
	[GetHashKey("stt_prop_race_start_line_03")] = true,
	[GetHashKey("stt_prop_race_start_line_03b")] = true,
	[GetHashKey("stt_prop_race_tannoy")] = true,
	[GetHashKey("stt_prop_ramp_adj_flip_m")] = true,
	[GetHashKey("stt_prop_ramp_adj_flip_mb")] = true,
	[GetHashKey("stt_prop_ramp_adj_flip_s")] = true,
	[GetHashKey("stt_prop_ramp_adj_flip_sb")] = true,
	[GetHashKey("stt_prop_ramp_adj_hloop")] = true,
	[GetHashKey("stt_prop_ramp_adj_loop")] = true,
	[GetHashKey("stt_prop_ramp_jump_l")] = true,
	[GetHashKey("stt_prop_ramp_jump_m")] = true,
	[GetHashKey("stt_prop_ramp_jump_s")] = true,
	[GetHashKey("stt_prop_ramp_jump_xl")] = true,
	[GetHashKey("stt_prop_ramp_jump_xs")] = true,
	[GetHashKey("stt_prop_ramp_jump_xxl")] = true,
	[GetHashKey("stt_prop_ramp_multi_loop_rb")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l_l")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l_m")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l_s")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l_xxl")] = true,
	[GetHashKey("stt_prop_ramp_spiral_m")] = true,
	[GetHashKey("stt_prop_ramp_spiral_s")] = true,
	[GetHashKey("stt_prop_ramp_spiral_xxl")] = true,
	[GetHashKey("stt_prop_sign_circuit_01")] = true,
	[GetHashKey("stt_prop_sign_circuit_02")] = true,
	[GetHashKey("stt_prop_sign_circuit_03")] = true,
	[GetHashKey("stt_prop_sign_circuit_04")] = true,
	[GetHashKey("stt_prop_sign_circuit_05")] = true,
	[GetHashKey("stt_prop_sign_circuit_06")] = true,
	[GetHashKey("stt_prop_sign_circuit_07")] = true,
	[GetHashKey("stt_prop_sign_circuit_08")] = true,
	[GetHashKey("stt_prop_sign_circuit_09")] = true,
	[GetHashKey("stt_prop_sign_circuit_10")] = true,
	[GetHashKey("stt_prop_sign_circuit_11")] = true,
	[GetHashKey("stt_prop_sign_circuit_11b")] = true,
	[GetHashKey("stt_prop_sign_circuit_12")] = true,
	[GetHashKey("stt_prop_sign_circuit_13")] = true,
	[GetHashKey("stt_prop_sign_circuit_13b")] = true,
	[GetHashKey("stt_prop_sign_circuit_14")] = true,
	[GetHashKey("stt_prop_sign_circuit_14b")] = true,
	[GetHashKey("stt_prop_sign_circuit_15")] = true,
	[GetHashKey("stt_prop_slow_down")] = true,
	[GetHashKey("stt_prop_speakerstack_01a")] = true,
	[GetHashKey("stt_prop_startline_gantry")] = true,
	[GetHashKey("stt_prop_stunt_bblock_huge_01")] = true,
	[GetHashKey("stt_prop_stunt_bblock_huge_02")] = true,
	[GetHashKey("stt_prop_stunt_bblock_huge_03")] = true,
	[GetHashKey("stt_prop_stunt_bblock_huge_04")] = true,
	[GetHashKey("stt_prop_stunt_bblock_huge_05")] = true,
	[GetHashKey("stt_prop_stunt_bblock_hump_01")] = true,
	[GetHashKey("stt_prop_stunt_bblock_hump_02")] = true,
	[GetHashKey("stt_prop_stunt_bblock_lrg1")] = true,
	[GetHashKey("stt_prop_stunt_bblock_lrg2")] = true,
	[GetHashKey("stt_prop_stunt_bblock_lrg3")] = true,
	[GetHashKey("stt_prop_stunt_bblock_mdm1")] = true,
	[GetHashKey("stt_prop_stunt_bblock_mdm2")] = true,
	[GetHashKey("stt_prop_stunt_bblock_mdm3")] = true,
	[GetHashKey("stt_prop_stunt_bblock_qp")] = true,
	[GetHashKey("stt_prop_stunt_bblock_qp2")] = true,
	[GetHashKey("stt_prop_stunt_bblock_qp3")] = true,
	[GetHashKey("stt_prop_stunt_bblock_sml1")] = true,
	[GetHashKey("stt_prop_stunt_bblock_sml2")] = true,
	[GetHashKey("stt_prop_stunt_bblock_sml3")] = true,
	[GetHashKey("stt_prop_stunt_bblock_xl1")] = true,
	[GetHashKey("stt_prop_stunt_bblock_xl2")] = true,
	[GetHashKey("stt_prop_stunt_bblock_xl3")] = true,
	[GetHashKey("stt_prop_stunt_bowling_ball")] = true,
	[GetHashKey("stt_prop_stunt_bowling_pin")] = true,
	[GetHashKey("stt_prop_stunt_bowlpin_stand")] = true,
	[GetHashKey("stt_prop_stunt_domino")] = true,
	[GetHashKey("stt_prop_stunt_jump15")] = true,
	[GetHashKey("stt_prop_stunt_jump30")] = true,
	[GetHashKey("stt_prop_stunt_jump45")] = true,
	[GetHashKey("stt_prop_stunt_jump_l")] = true,
	[GetHashKey("stt_prop_stunt_jump_lb")] = true,
	[GetHashKey("stt_prop_stunt_jump_loop")] = true,
	[GetHashKey("stt_prop_stunt_jump_m")] = true,
	[GetHashKey("stt_prop_stunt_jump_mb")] = true,
	[GetHashKey("stt_prop_stunt_jump_s")] = true,
	[GetHashKey("stt_prop_stunt_jump_sb")] = true,
	[GetHashKey("stt_prop_stunt_landing_zone_01")] = true,
	[GetHashKey("stt_prop_stunt_ramp")] = true,
	[GetHashKey("stt_prop_stunt_soccer_ball")] = true,
	[GetHashKey("stt_prop_stunt_soccer_goal")] = true,
	[GetHashKey("stt_prop_stunt_soccer_lball")] = true,
	[GetHashKey("stt_prop_stunt_soccer_sball")] = true,
	[GetHashKey("stt_prop_stunt_target")] = true,
	[GetHashKey("stt_prop_stunt_target_small")] = true,
	[GetHashKey("stt_prop_stunt_track_bumps")] = true,
	[GetHashKey("stt_prop_stunt_track_cutout")] = true,
	[GetHashKey("stt_prop_stunt_track_dwlink")] = true,
	[GetHashKey("stt_prop_stunt_track_dwlink_02")] = true,
	[GetHashKey("stt_prop_stunt_track_dwsh15")] = true,
	[GetHashKey("stt_prop_stunt_track_dwshort")] = true,
	[GetHashKey("stt_prop_stunt_track_dwslope15")] = true,
	[GetHashKey("stt_prop_stunt_track_dwslope30")] = true,
	[GetHashKey("stt_prop_stunt_track_dwslope45")] = true,
	[GetHashKey("stt_prop_stunt_track_dwturn")] = true,
	[GetHashKey("stt_prop_stunt_track_dwuturn")] = true,
	[GetHashKey("stt_prop_stunt_track_exshort")] = true,
	[GetHashKey("stt_prop_stunt_track_fork")] = true,
	[GetHashKey("stt_prop_stunt_track_funlng")] = true,
	[GetHashKey("stt_prop_stunt_track_funnel")] = true,
	[GetHashKey("stt_prop_stunt_track_hill")] = true,
	[GetHashKey("stt_prop_stunt_track_hill2")] = true,
	[GetHashKey("stt_prop_stunt_track_jump")] = true,
	[GetHashKey("stt_prop_stunt_track_link")] = true,
	[GetHashKey("stt_prop_stunt_track_otake")] = true,
	[GetHashKey("stt_prop_stunt_track_sh15")] = true,
	[GetHashKey("stt_prop_stunt_track_sh30")] = true,
	[GetHashKey("stt_prop_stunt_track_sh45")] = true,
	[GetHashKey("stt_prop_stunt_track_sh45_a")] = true,
	[GetHashKey("stt_prop_stunt_track_short")] = true,
	[GetHashKey("stt_prop_stunt_track_slope15")] = true,
	[GetHashKey("stt_prop_stunt_track_slope30")] = true,
	[GetHashKey("stt_prop_stunt_track_slope45")] = true,
	[GetHashKey("stt_prop_stunt_track_start")] = true,
	[GetHashKey("stt_prop_stunt_track_start_02")] = true,
	[GetHashKey("stt_prop_stunt_track_straight")] = true,
	[GetHashKey("stt_prop_stunt_track_straightice")] = true,
	[GetHashKey("stt_prop_stunt_track_st_01")] = true,
	[GetHashKey("stt_prop_stunt_track_st_02")] = true,
	[GetHashKey("stt_prop_stunt_track_turn")] = true,
	[GetHashKey("stt_prop_stunt_track_turnice")] = true,
	[GetHashKey("stt_prop_stunt_track_uturn")] = true,
	[GetHashKey("stt_prop_stunt_tube_crn")] = true,
	[GetHashKey("stt_prop_stunt_tube_crn2")] = true,
	[GetHashKey("stt_prop_stunt_tube_crn_15d")] = true,
	[GetHashKey("stt_prop_stunt_tube_crn_30d")] = true,
	[GetHashKey("stt_prop_stunt_tube_crn_5d")] = true,
	[GetHashKey("stt_prop_stunt_tube_cross")] = true,
	[GetHashKey("stt_prop_stunt_tube_end")] = true,
	[GetHashKey("stt_prop_stunt_tube_ent")] = true,
	[GetHashKey("stt_prop_stunt_tube_fn_01")] = true,
	[GetHashKey("stt_prop_stunt_tube_fn_02")] = true,
	[GetHashKey("stt_prop_stunt_tube_fn_03")] = true,
	[GetHashKey("stt_prop_stunt_tube_fn_04")] = true,
	[GetHashKey("stt_prop_stunt_tube_fn_05")] = true,
	[GetHashKey("stt_prop_stunt_tube_fork")] = true,
	[GetHashKey("stt_prop_stunt_tube_gap_01")] = true,
	[GetHashKey("stt_prop_stunt_tube_gap_02")] = true,
	[GetHashKey("stt_prop_stunt_tube_gap_03")] = true,
	[GetHashKey("stt_prop_stunt_tube_hg")] = true,
	[GetHashKey("stt_prop_stunt_tube_jmp")] = true,
	[GetHashKey("stt_prop_stunt_tube_jmp2")] = true,
	[GetHashKey("stt_prop_stunt_tube_l")] = true,
	[GetHashKey("stt_prop_stunt_tube_m")] = true,
	[GetHashKey("stt_prop_stunt_tube_qg")] = true,
	[GetHashKey("stt_prop_stunt_tube_s")] = true,
	[GetHashKey("stt_prop_stunt_tube_speed")] = true,
	[GetHashKey("stt_prop_stunt_tube_speeda")] = true,
	[GetHashKey("stt_prop_stunt_tube_speedb")] = true,
	[GetHashKey("stt_prop_stunt_tube_xs")] = true,
	[GetHashKey("stt_prop_stunt_tube_xxs")] = true,
	[GetHashKey("stt_prop_stunt_wideramp")] = true,
	[GetHashKey("stt_prop_track_bend2_bar_l")] = true,
	[GetHashKey("stt_prop_track_bend2_bar_l_b")] = true,
	[GetHashKey("stt_prop_track_bend2_l")] = true,
	[GetHashKey("stt_prop_track_bend2_l_b")] = true,
	[GetHashKey("stt_prop_track_bend_15d")] = true,
	[GetHashKey("stt_prop_track_bend_15d_bar")] = true,
	[GetHashKey("stt_prop_track_bend_180d")] = true,
	[GetHashKey("stt_prop_track_bend_180d_bar")] = true,
	[GetHashKey("stt_prop_track_bend_30d")] = true,
	[GetHashKey("stt_prop_track_bend_30d_bar")] = true,
	[GetHashKey("stt_prop_track_bend_5d")] = true,
	[GetHashKey("stt_prop_track_bend_5d_bar")] = true,
	[GetHashKey("stt_prop_track_bend_bar_l")] = true,
	[GetHashKey("stt_prop_track_bend_bar_l_b")] = true,
	[GetHashKey("stt_prop_track_bend_bar_m")] = true,
	[GetHashKey("stt_prop_track_bend_l")] = true,
	[GetHashKey("stt_prop_track_bend_l_b")] = true,
	[GetHashKey("stt_prop_track_bend_m")] = true,
	[GetHashKey("stt_prop_track_block_01")] = true,
	[GetHashKey("stt_prop_track_block_02")] = true,
	[GetHashKey("stt_prop_track_block_03")] = true,
	[GetHashKey("stt_prop_track_chicane_l")] = true,
	[GetHashKey("stt_prop_track_chicane_l_02")] = true,
	[GetHashKey("stt_prop_track_chicane_r")] = true,
	[GetHashKey("stt_prop_track_chicane_r_02")] = true,
	[GetHashKey("stt_prop_track_cross")] = true,
	[GetHashKey("stt_prop_track_cross_bar")] = true,
	[GetHashKey("stt_prop_track_fork")] = true,
	[GetHashKey("stt_prop_track_fork_bar")] = true,
	[GetHashKey("stt_prop_track_funnel")] = true,
	[GetHashKey("stt_prop_track_funnel_ads_01a")] = true,
	[GetHashKey("stt_prop_track_funnel_ads_01b")] = true,
	[GetHashKey("stt_prop_track_funnel_ads_01c")] = true,
	[GetHashKey("stt_prop_track_jump_01a")] = true,
	[GetHashKey("stt_prop_track_jump_01b")] = true,
	[GetHashKey("stt_prop_track_jump_01c")] = true,
	[GetHashKey("stt_prop_track_jump_02a")] = true,
	[GetHashKey("stt_prop_track_jump_02b")] = true,
	[GetHashKey("stt_prop_track_jump_02c")] = true,
	[GetHashKey("stt_prop_track_link")] = true,
	[GetHashKey("stt_prop_track_slowdown")] = true,
	[GetHashKey("stt_prop_track_slowdown_t1")] = true,
	[GetHashKey("stt_prop_track_slowdown_t2")] = true,
	[GetHashKey("stt_prop_track_speedup")] = true,
	[GetHashKey("stt_prop_track_speedup_t1")] = true,
	[GetHashKey("stt_prop_track_speedup_t2")] = true,
	[GetHashKey("stt_prop_track_start")] = true,
	[GetHashKey("stt_prop_track_start_02")] = true,
	[GetHashKey("stt_prop_track_stop_sign")] = true,
	[GetHashKey("stt_prop_track_straight_bar_l")] = true,
	[GetHashKey("stt_prop_track_straight_bar_m")] = true,
	[GetHashKey("stt_prop_track_straight_bar_s")] = true,
	[GetHashKey("stt_prop_track_straight_l")] = true,
	[GetHashKey("stt_prop_track_straight_lm")] = true,
	[GetHashKey("stt_prop_track_straight_lm_bar")] = true,
	[GetHashKey("stt_prop_track_straight_m")] = true,
	[GetHashKey("stt_prop_track_straight_s")] = true,
	[GetHashKey("stt_prop_track_tube_01")] = true,
	[GetHashKey("stt_prop_track_tube_02")] = true,
	[GetHashKey("stt_prop_tyre_wall_01")] = true,
	[GetHashKey("stt_prop_tyre_wall_010")] = true,
	[GetHashKey("stt_prop_tyre_wall_011")] = true,
	[GetHashKey("stt_prop_tyre_wall_012")] = true,
	[GetHashKey("stt_prop_tyre_wall_013")] = true,
	[GetHashKey("stt_prop_tyre_wall_014")] = true,
	[GetHashKey("stt_prop_tyre_wall_015")] = true,
	[GetHashKey("stt_prop_tyre_wall_02")] = true,
	[GetHashKey("stt_prop_tyre_wall_03")] = true,
	[GetHashKey("stt_prop_tyre_wall_04")] = true,
	[GetHashKey("stt_prop_tyre_wall_05")] = true,
	[GetHashKey("stt_prop_tyre_wall_06")] = true,
	[GetHashKey("stt_prop_tyre_wall_07")] = true,
	[GetHashKey("stt_prop_tyre_wall_08")] = true,
	[GetHashKey("stt_prop_tyre_wall_09")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l010")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l012")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l013")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l014")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l015")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l018")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l019")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l020")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l04")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l05")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l06")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l07")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l08")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l1")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l16")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l17")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l2")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l3")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r010")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r011")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r012")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r013")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r014")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r015")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r016")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r017")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r018")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r019")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r04")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r05")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r06")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r07")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r08")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r09")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r1")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r2")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r3")] = true,
	[GetHashKey("stt_prop_wallride_01")] = true,
	[GetHashKey("stt_prop_wallride_01b")] = true,
	[GetHashKey("stt_prop_wallride_02")] = true,
	[GetHashKey("stt_prop_wallride_02b")] = true,
	[GetHashKey("stt_prop_wallride_04")] = true,
	[GetHashKey("stt_prop_wallride_05")] = true,
	[GetHashKey("stt_prop_wallride_05b")] = true,
	[GetHashKey("stt_prop_wallride_45l")] = true,
	[GetHashKey("stt_prop_wallride_45la")] = true,
	[GetHashKey("stt_prop_wallride_45r")] = true,
	[GetHashKey("stt_prop_wallride_45ra")] = true,
	[GetHashKey("stt_prop_wallride_90l")] = true,
	[GetHashKey("stt_prop_wallride_90lb")] = true,
	[GetHashKey("stt_prop_wallride_90r")] = true,
	[GetHashKey("stt_prop_wallride_90rb")] = true,
	[GetHashKey("prop_fnclink_05crnr1")] = true,
	[GetHashKey("xs_prop_hamburgher_wl")] = true,
	[GetHashKey("xs_prop_plastic_bottle_wl")] = true,
	[GetHashKey("stt_prop_stunt_track_dwslope15")] = true,
	[GetHashKey("stt_prop_stunt_track_dwslope30")] = true,
	[GetHashKey("stt_prop_stunt_track_dwslope45")] = true,
	[GetHashKey("stt_prop_stunt_track_dwturn")] = true,
	[GetHashKey("stt_prop_stunt_track_fork")] = true,
	[GetHashKey("stt_prop_stunt_track_dwuturn")] = true,
	[GetHashKey("stt_prop_stunt_track_exshort")] = true,
	[GetHashKey("stt_prop_stunt_track_hill")] = true,
	[GetHashKey("stt_prop_stunt_track_funnel")] = true,
	[GetHashKey("stt_prop_stunt_track_funlng")] = true,
}